In [4]:
import pandas as pd
import numpy as np
data = pd.read_csv("data.csv")

In [14]:
data.columns

Index(['label_p0_x', 'label_p0_y', 'label_p1_x', 'label_p1_y', 'label_p2_x',
       'label_p2_y', 'label_p3_x', 'label_p3_y', 'prediction_p0_x',
       'prediction_p0_y', 'prediction_p1_x', 'prediction_p1_y',
       'prediction_p2_x', 'prediction_p2_y', 'prediction_p3_x',
       'prediction_p3_y'],
      dtype='object')

In [5]:
boxA = data.filter(like = "label", axis = 1)
boxB = data.filter(like = 'prediction', axis = 1)

In [6]:
def clip(subject_polygon, clip_polygon):
    def inside(point):
        cond1 = (clip_vertex_point[0]-clip_polygon_last_point[0])*(point[1]-clip_polygon_last_point[1])
        cond2 = (clip_vertex_point[1]-clip_polygon_last_point[1])*(point[0]-clip_polygon_last_point[0])
        return cond1 > cond2

    def computeIntersection():
        dc = [ clip_polygon_last_point[0] - clip_vertex_point[0], clip_polygon_last_point[1] - clip_vertex_point[1] ]
        dp = [point_s[0] -point_e[0], point_s[1] -point_e[1] ]
        n1 = clip_polygon_last_point[0] * clip_vertex_point[1] - clip_polygon_last_point[1] * clip_vertex_point[0]
        n2 = point_s[0] *point_e[1] - point_s[1] *point_e[0] 
        n3 = 1.0 / (dc[0] * dp[1] - dc[1] * dp[0])
        return np.array([(n1*dp[0] - n2*dc[0]) * n3, (n1*dp[1] - n2*dc[1]) * n3])

    outputList = subject_polygon
    clip_polygon_last_point = clip_polygon[-1]

    for clipVertex in clip_polygon:
        clip_vertex_point = clipVertex
        inputList = outputList
        outputList = []
        point_s= inputList[-1]

        for subjectVertex in inputList:
            point_e = subjectVertex
            if inside(point_e):
                if not inside(point_s):
                    outputList.append(computeIntersection())
                outputList.append(point_e)
            elif inside(point_s):
                outputList.append(computeIntersection())
            point_s=point_e
        clip_polygon_last_point = clip_vertex_point
    return(list(map(list, zip(*outputList))))

In [7]:
def shoelace_formula_area(x,y):
    """
    x,y - coordinates
    """
    main_area = np.dot(x[:-1],y[1:]) - np.dot(x[1:], y[:-1])
    edge_terms = x[-1]*y[0] - y[-1]*x[0]
    return 0.5*abs(main_area + edge_terms)

In [8]:
shoelace_formula_area(boxB.values[1][::2], boxB.values[1][1::2])

2502964.242136045

In [13]:
list(zip(boxB.values[1][::2], boxB.values[1][1::2]))

[(320.46087646484375, 199.69613647460938),
 (2307.78955078125, 206.8181304931641),
 (2307.19287109375, 1476.7396240234375),
 (330.70074462890625, 1455.6529541015625)]

In [9]:
shoelace_formula_area(boxA.values[1][::2], boxA.values[1][1::2])

2453824.6999999997

In [12]:
for x,y in zip(boxA.values,boxB.values):
    points_label = list(zip(x[::2], x[1::2]))
    points_prediction = list(zip(y[::2], y[1::2]))
    intersection = clip(points_label, points_prediction)
    polygon_area(list(map(list, zip(*intersection)))[0],list(map(list, zip(*inter)))[1])

[ 234.    144.4  1655.94  151.67 1653.   1050.    238.4  1060.  ]
[ 325.8  217.3 2304.1  199.  2298.  1460.1  334.1 1446. ]
[ 812.    747.9  3228.85  751.58 3243.59 2291.59  789.9  2284.22]
[  92.4   98.5 2687.8   94.1 2694.5 1737.5   90.3 1726.3]
[ 116.1  110.2 2728.7  117.3 2724.  1761.1  106.7 1756.6]
[ 122.8  113.7 2705.8  123.  2701.3 1759.1   85.6 1738.2]
[ 421.7  447.4 2989.6  414.6 2995.4 2034.   457.5 2037. ]
[ 385.6   248.3  2758.9   248.3  2758.9  1757.5   388.01 1774.55]
[ 895.9  501.1 2679.4  617.4 2798.7 1732.8  669.3 1568.6]
[ 815.4   856.   1960.67  855.97 2008.2  1509.1   699.1  1514.9 ]
[ 827.34  772.46 2166.46  769.48 2211.2  1607.5   714.   1595.6 ]
[1030.1  1005.1  2062.1   927.5  2118.7  1553.7   976.46 1622.46]
[ 809.4  835.1 2282.6  841.  2533.3 1464.2  505.2 1461.4]
[ 287.   181.3 2009.8  183.6 2017.2 1283.5  291.7 1280.4]
[ 518.4  761.1 3340.5  733.1 3499.6 2553.1  237.7 2508.9]
[ 372.4   245.2  2593.    226.9  2606.8  1647.7   365.52 1650.01]
[ 254.8   166.6 

In [10]:
inter = clip(temp,temp2)

NameError: name 'temp' is not defined

In [113]:
polygon_area(list(map(list, zip(*inter)))[0],list(map(list, zip(*inter)))[1])

2446104.9542677733

In [1]:
boxA

NameError: name 'boxA' is not defined